image:
  repository: your-dockerhub-username/komoot-tour-browser
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: ''
  host: komoot.sebse.de
  tls:
    enabled: true
    secretName: komoot-tour-browser-tls
  annotations: {}

resources:
  requests:
    cpu: 10m
    memory: 16Mi
  limits:
    cpu: 50m
    memory: 32Mi

podAnnotations: {}

nodeSelector: {}

tolerations: []

affinity: {}
