export const SPORT_ICONS = Object.freeze({
  hike: '🥾',
  hiking: '🥾',
  mountaineering: '⛰️',
  touringbicycle: '🚴',
  racebike: '🚴‍♂️',
  gravel_cycling: '🚴',
  mtb: '🚵',
  mtb_easy: '🚵',
  mtb_advanced: '🚵',
  mtb_enduro: '🚵',
  e_touringbicycle: '⚡',
  e_mtb: '⚡',
  e_racebike: '⚡',
  jogging: '🏃',
  running: '🏃',
  nordic: '⛷️',
  nordic_walking: '🚶',
  skitour: '⛷️',
  snowshoe: '🏔️',
  climbing: '🧗',
} as const);

export const CONFIG = Object.freeze({
  API_BASE: 'https://api.komoot.de',
  API_WWW: 'https://www.komoot.com/api',
  PAGE_LIMIT: 500,
  TRACKS_EAGER_LIMIT: 30,
  TILE_URL:
    'https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}{r}.png',
  TILE_ATTR:
    '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> &copy; <a href="https://carto.com/">CARTO</a>',
  COLORS: [
    '#4a6cf7',
    '#e74c3c',
    '#2ecc71',
    '#f39c12',
    '#9b59b6',
    '#1abc9c',
    '#e67e22',
    '#3498db',
    '#e91e63',
    '#00bcd4',
  ],
  DEFAULT_CENTER: [48.0, 12.0] as [number, number],
  DEFAULT_ZOOM: 6,
  FILTER_DEBOUNCE_MS: 200,
  ELEVATION_CANVAS_HEIGHT: 140,
  ELEVATION_SAMPLES: 600,
  LOCALE: navigator.language?.split('-')[0] || 'en',
  MAP_STYLES: {
    TRACK_WEIGHT: 3,
    TRACK_OPACITY: 0.85,
    MARKER_RADIUS: 7,
    MARKER_WEIGHT: 2,
    START_MARKER_RADIUS: 5,
    START_MARKER_WEIGHT: 2,
  },
});
